name: CI

on:
  push:
    branches: [ "main", "dev" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: docker build
        run: docker build -t tests .
      - name: run docker
        run: docker run -t --rm tests
